SHOW DATABASES;

USE CRUNCHBASE_BASIC_COMPANY_DATA;

SHOW SCHEMAS;

USE SCHEMA PUBLIC;

SHOW TABLES;

SHOW VIEWS;

SELECT * FROM ORGANIZATION_SUMMARY LIMIT 10;

DESC VIEW ORGANIZATION_SUMMARY;

SELECT COUNT(*) amountrows FROM ORGANIZATION_SUMMARY;

SELECT DISTINCT type FROM ORGANIZATION_SUMMARY;

SELECT COUNT(DISTINCT NAME) AS Nr_unique_name FROM ORGANIZATION_SUMMARY;

SELECT COUNT(DISTINCT COUNTRY_CODE) AS Nr_unique_country FROM ORGANIZATION_SUMMARY;

SELECT
    COUNTRY_CODE,
    COUNT(*) AS NUMBER_OF_ORGANIZATIONS
FROM ORGANIZATION_SUMMARY
GROUP BY COUNTRY_CODE
ORDER BY NUMBER_OF_ORGANIZATIONS DESC;
