SHOW DATABASES;

USE DATABASE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;

SHOW SCHEMAS;

SHOW TABLES;

SHOW VIEWS;

USE SCHEMA DATAFEEDS;

SHOW COLUMNS IN TABLE GOOGLE_KEYWORDS;

SELECT data_type FROM GOOGLE_KEYWORDS;