SHOW DATABASES;

USE DATABASE GOOGLE_KEYWORDS_SEARCH_DATASET__DISCOVER_ALL_SEARCHES_ON_GOOGLE;

SHOW SCHEMAS;

USE SCHEMA DATAFEEDS;

SHOW TABLES;

SHOW VIEWS;

SHOW COLUMNS IN TABLE GOOGLE_KEYWORDS;

SELECT * FROM GOOGLE_KEYWORDS LIMIT 10;